import fs from "node:fs";

const files = process.argv.slice(2);
if (!files.length) throw new Error("Pass one or more UTF-8 text files");

const pairs = [
  ["青空服装管理系统 NG", "Aozora Outfit Management System NG"],
  ["打开或关闭青空服装管理系统 NG", "Open or close Aozora Outfit Management System NG"],
  ["打开/关闭青空服装管理系统 NG", "Open/Close Aozora Outfit Management System NG"],
  ["青空的服装管理系统", "Aozora Outfit Management System NG"],
  ["打开/关闭管理系统", "Open/Close Management System"],
  ["打开或关闭Aozora Outfit Management System", "Open or close Aozora Outfit Management System NG"],
  ["打开/关闭Aozora Outfit Management System", "Open/Close Aozora Outfit Management System NG"],
  ["打开Aozora Outfit Management System", "Open Aozora Outfit Management System NG"],
  ["打开或关闭青空的服装管理系统", "Open or close Aozora Outfit Management System NG"],
  ["打开/关闭青空的服装管理系统", "Open/Close Aozora Outfit Management System NG"],
  ["打开青空的服装管理系统", "Open Aozora Outfit Management System NG"],
  ["本系统由 Fallout4 Outfit Manager 全面升级而来，在保留原有套装管理能力的基础上，重新构建了试穿、搭配、材质交换与角色换装流程", "Upgraded from Fallout4 Outfit Manager with redesigned outfit preview, styling, material swap, and character dressing workflows"],
  ["支持玩家与NPC的套装保存、快速换装、实时试穿、服装工作台编辑以及独立材质交换款生成", "Save and switch outfits for the player and NPCs, preview changes live, edit in the Outfit Studio, and create independent material variants"],
  ["为兼容旧版设置与套装数据，插件文件、MCM标识和数据目录继续沿用 OutfitManager 名称", "Plugin files, MCM identifiers, and data folders retain the OutfitManager name for compatibility with existing settings and outfits"],
  ["套装保存、实时试穿、材质定制与角色换装", "Outfit saving, live preview, material customization, and character dressing"],
  ["在服装管理界面确认穿戴，或使用随机换装、装备上一套、装备下一套成功换装后，该套装会成为当前活跃套装。以下功能都以当前活跃套装为起点执行。", "An outfit becomes active after it is confirmed in the UI or equipped with Random, Previous, or Next. The actions below start from that active outfit."],
  ["从当前活跃套装开始，循环向前装备一套符合目标性别的可用套装。", "Cycle backward from the active outfit to an available outfit matching the target."],
  ["从当前活跃套装开始，循环向后装备一套符合目标性别的可用套装。", "Cycle forward from the active outfit to an available outfit matching the target."],
  ["将目标当前穿着保存到当前活跃套装；没有活跃套装时保存到第一个空位。", "Save the target's current clothing to the active outfit, or the first empty slot when none is active."],
  ["将当前活跃套装重新装备到目标身上。", "Equip the active outfit on the target again."],
  ["对目标随机更换一套符合其性别的已保存套装。", "Equip the target with a random saved outfit that matches them."],
  ["显示换装完成、保存成功等状态通知。", "Show status notifications for dressing and saving."],
  ["开启后，保存套装时会记录角色当前装备的武器、普通改造与传奇效果", "When enabled, saved outfits include the equipped weapon, standard modifications, and legendary effects"],
  ["应用套装时不会复用背包中的武器，而是按照保存记录生成一把新的独立武器", "Applying an outfit creates a new independent weapon from the saved record instead of reusing one from inventory"],
  ["仅过滤可识别的 Fallout4.esm 原版唯一或特殊改装，普通改造与传奇效果会保留", "Recognizable unique or special Fallout4.esm modifications are filtered; standard modifications and legendary effects are retained"],
  ["MOD 武器以及基础记录、脚本或特殊数据自带的效果无法通用识别，仍可能保留", "Effects built into modded weapons, base records, scripts, or special data cannot be identified universally and may remain"],
  ["玩家或NPC没有对应弹药时，系统会静默补充3个弹匣，最少30发、最多180发；每种弹药对玩家及每名NPC在同一存档中只补充一次，切换存档后分别重新记录", "When the player or an NPC lacks the required ammo, the system silently supplies three magazines, from 30 to 180 rounds. Each ammo type is supplied once per actor per save"],
  ["切换其他套装时会清理上一次由系统生成的武器；关闭后工作台不会加载武器，保存与换装只处理服装", "Switching outfits removes the last system-generated weapon. When disabled, the studio does not load weapons and only clothing is saved or equipped"],
  ["开启后记录当前装备的武器、普通改造与传奇效果，并在应用套装时生成新的独立武器；关闭后工作台不加载武器", "Save the equipped weapon, standard modifications, and legendary effects, then create a new independent weapon when applying the outfit. Disabled means the studio does not load weapons"],
  ["进入工作台前显示裸露内容提示。无论是否显示此提示，工作台都会从角色的当前真实穿着开始编辑。默认开启。", "Show a nudity warning before entering the studio. The studio always starts from the character's actual outfit. Enabled by default."],
  ["工作台会从角色的当前真实穿着开始搭配。", "The studio starts from the character's actual outfit."],
  ["编辑期间，如果脱下不带内衣的服装，画面可能出现裸露内容。是否进入服装工作台？", "Removing clothing without built-in underwear may reveal nudity while editing. Enter the Outfit Studio?"],
  ["可在 MCM「提示与确认」中关闭此提示。", "This warning can be disabled under Prompts & Confirmations in MCM."],
  ["外部中文命名：打开 slot-names.txt（UTF-8），按 <b>001 = 名称</b> 的格式改等号右侧；下次打开菜单自动刷新。游戏内输入建议只用英文；留空即可恢复默认名称。", "External naming: open slot-names.txt (UTF-8) and edit the text after the equals sign using <b>001 = Name</b>. Names refresh when the menu reopens. Leave the value empty to restore the default name."],
  ["发现失效记录，原始套装暂未修改", "Missing records found; the original outfit has not been changed"],
  ["无论选择哪一项，都只会清理当前套装中的失效记录，并保留恢复备份。", "Either choice removes only missing records from this outfit and keeps a recovery backup."],
  ["无论选择哪一项，都只会清理这个套装中的失效记录，并保留恢复备份", "Either choice removes only missing records from this outfit and keeps a recovery backup"],
  ["继续穿戴可能让角色只穿上剩余部分。", "Continuing may leave the character wearing only the remaining items."],
  ["这个 NPC 使用了共享模板。继续换装可能会让其他同类 NPC 一起发生变化。", "This NPC uses a shared template. Changing their outfit may also affect similar NPCs."],
  ["这个 NPC 使用了共享模板\n继续换装可能会让其他同类 NPC 一起发生变化", "This NPC uses a shared template\nChanging their outfit may also affect similar NPCs"],
  ["目标正由任务、场景或特殊动画控制，暂时不能换装", "The target is controlled by a quest, scene, or special animation and cannot change outfits now"],
  ["目标正由任务或特殊状态控制，暂时不能换装", "The target is controlled by a quest or special state and cannot change outfits now"],
  ["目标必须保持站立才能进入服装工作台", "The target must be standing to enter the Outfit Studio"],
  ["这个 NPC 可能使用共享模板，换装可能影响其他同类 NPC", "This NPC may use a shared template; changing outfits could affect similar NPCs"],
  ["服装管理器不能在动力甲状态下保存或换装。请先离开动力甲。", "Outfits cannot be saved or equipped while using Power Armor. Exit Power Armor first."],
  ["Prisma UI Framework 暂未连接。", "Prisma UI Framework is not connected."],
  ["服装管理器 UI 暂未连接。", "The outfit manager UI is not connected."],
  ["请确认 Prisma UI Framework 已安装，并使用带 Prisma 接入的 OutfitManager.dll。", "Confirm that Prisma UI Framework is installed and that the Prisma-enabled OutfitManager.dll is in use."],
  ["界面正在准备中，请稍后再试。", "The interface is preparing. Try again shortly."],
  ["首次启动资源加载中", "Loading resources for the first launch"],
  ["正在保存当前设置", "Saving current settings"],
  ["正在整理角色状态，请稍候", "Finalizing character state. Please wait"],
  ["请选择一项功能开始。", "Choose an action to begin."],
  ["想要做什么呢？请选择一项功能开始。", "What would you like to do? Choose an action to begin."],
  ["想要做什么？", "What would you like to do?"],
  ["服装管理 / 当前角色", "Outfit Management / Current Character"],
  ["服装管理 / 已保存套装", "Outfit Management / Saved Outfits"],
  ["服装管理 / 低频操作", "Outfit Management / More Actions"],
  ["套装管理 / 附近角色", "Outfit Management / Nearby Characters"],
  ["人物显示：当前真实穿着", "Character: Actual Outfit"],
  ["当前真实穿着", "Actual Outfit"],
  ["当前编辑搭配", "Current Draft"],
  ["工作台编辑搭配", "Studio Draft"],
  ["保存当前穿着", "Save Current Outfit"],
  ["恢复角色默认服装", "Restore Character Default"],
  ["恢复默认服装", "Restore Default Outfit"],
  ["管理套装：浏览、试穿、保存当前穿着、命名或清空套装。", "Manage Outfits: browse, preview, save, rename, or clear outfits."],
  ["确认穿戴：将右侧正在试穿的套装正式装备到角色身上。", "Confirm Outfit: equip the outfit currently being previewed."],
  ["随机试穿：从适合当前角色的已保存套装中抽取一套。", "Random Preview: choose a saved outfit that matches the current character."],
  ["服装工作台：从角色的当前真实穿着开始搭配，可逐件试穿并调整材质。", "Outfit Studio: start from the actual outfit, preview individual items, and adjust materials."],
  ["选择目标：切换玩家或附近 NPC。NPC 预览受距离和状态限制。", "Select Target: switch between the player and nearby NPCs. NPC preview depends on distance and state."],
  ["更多功能：进入恢复默认等低频操作。", "More Actions: access less frequently used actions."],
  ["恢复默认服装：移除本模组管理的衣物，恢复目标的默认服装。", "Restore Default Outfit: remove managed items and restore the target's default outfit."],
  ["返回服装管理主页面。", "Return to the main outfit management page."],
  ["关闭前会询问是否确认穿戴当前试穿。", "You will be asked whether to equip the current preview before closing."],
  ["关闭菜单并返回游戏。", "Close the menu and return to the game."],
  ["这里还没有保存套装", "No outfits saved here yet"],
  ["穿好喜欢的搭配后，可以把它保存到这个槽位", "Dress the character, then save the look to this slot"],
  ["附近没有可选择的角色", "No eligible characters nearby"],
  ["靠近一名 NPC 后再回来看看", "Move closer to an NPC and try again"],
  ["挑选离你比较近的目标，试衣服效果才会好哦。", "Choose a nearby target for the most reliable preview."],
  ["选择附近目标", "Select a Nearby Target"],
  ["武器保存尚未开启", "Weapon saving is disabled"],
  ["在 MCM 菜单中开启“保存武器”后，再进入工作台加载武器", "Enable Save Weapons in MCM, then reopen the studio to load weapons"],
  ["正在整理可用于搭配的服装", "Preparing clothing for the studio"],
  ["物品较多时需要一点时间，请稍等一下哦。", "Large inventories can take a moment. Please wait."],
  ["这个分类里没有服装", "No clothing in this category"],
  ["换个分类看看，或者先把服装放进角色背包", "Try another category or add clothing to the character's inventory"],
  ["正在整理这件服装的可用材质", "Preparing available materials"],
  ["第一次读取可能稍慢，请稍等一下哦。", "The first scan may take a moment. Please wait."],
  ["这件服装没有材质交换", "This item has no material swaps"],
  ["它仍然可以作为基础款正常试穿和保存", "It can still be previewed and saved as the base item"],
  ["试穿不会写入背包", "Previewing does not modify inventory"],
  ["生成后会作为永久命名物品加入玩家背包", "Generated variants are added to the player's inventory as permanent named items"],
  ["请先穿上再调材质", "Equip the item before changing its material"],
  ["武器会保留当前改装；材质交换仅适用于服装", "Weapons keep their current modifications; material swaps apply only to clothing"],
  ["当前试穿与角色的Actual Outfit不同，要确认穿戴这身Outfit再退出吗？", "The preview differs from the character's Actual Outfit. Equip it before closing?"],
  ["当前试穿与角色的当前真实穿着不同，要确认穿戴这身套装再退出吗？", "The preview differs from the character's actual outfit. Equip it before closing?"],
  ["当前材质只是临时试穿，要生成物品后保留吗？", "This material is only a preview. Generate a permanent item?"],
  ["当前编辑搭配发生了变化，要怎么处理呢？", "The studio draft has changed. What should happen next?"],
  ["是否移除本模组管理的衣物，并恢复角色默认状态？", "Remove managed items and restore the character's default state?"],
  ["此操作会删除其中保存的套装数据。", "This deletes the saved outfit data in this slot."],
  ["已经失效的服装或改装记录", "missing clothing or modification records"],
  ["当前「", "Current \""], ["」尚未被修改", "\" has not been changed"],
  ["选择「继续穿」后会穿上剩余内容", "Choose Continue to equip the remaining items"],
  ["这套搭配已经保存好啦", "This outfit has been saved"],
  ["这套搭配没有保存成功，再试一次吧。", "The outfit was not saved. Please try again."],
  ["保存失败：没有可用的空套装。", "Save failed: no empty outfit slot is available."],
  ["没有当前活跃套装，请先确认穿戴一套服装。", "No active outfit. Confirm an outfit first."],
  ["没有符合目标性别的其他套装", "No other saved outfit matches the target"],
  ["没有符合目标性别的套装", "No saved outfit matches the target"],
  ["没有符合目标性别的已保存套装。", "No saved outfit matches the target."],
  ["没有可用的已保存套装。", "No usable saved outfit is available."],
  ["当前目标没有可保存的服装", "The current target has no clothing that can be saved"],
  ["当前目标无法保存套装", "The current target cannot save an outfit"],
  ["写入套装文件失败", "Failed to write the outfit file"],
  ["套装备份或清理失败，原记录未修改", "Outfit backup or cleanup failed; the original record was not changed"],
  ["无法备份并更新这个套装", "Failed to back up and update this outfit"],
  ["无法读取这个套装，原记录未修改", "Unable to read this outfit; the original record was not changed"],
  ["已清理这个套装中的失效记录", "Missing records were removed from this outfit"],
  ["失效记录已清理，这个套装已没有可穿戴内容", "Missing records were removed; this outfit has no wearable items left"],
  ["槽位性别与当前目标不符", "The slot does not match the target"],
  ["套装中没有可穿戴内容", "The outfit has no wearable items"],
  ["换装操作正忙，请稍后重试", "An outfit operation is busy. Try again shortly"],
  ["战斗中不能换装", "Outfits cannot be changed during combat"],
  ["操作冷却中。", "This action is on cooldown."],
  ["换装冷却中。", "Outfit change is on cooldown."],
  ["随机换装冷却中。", "Random outfit is on cooldown."],
  ["随机功能冷却中。", "Random action is on cooldown."],
  ["还原功能冷却中。", "Restore is on cooldown."],
  ["菜单冷却中。", "The menu is on cooldown."],
  ["正在换装，请稍候。", "Changing outfit. Please wait."],
  ["正在随机换装，请稍候。", "Choosing a random outfit. Please wait."],
  ["正在选择套装...", "Choosing an outfit..."],
  ["正在还原套装...", "Restoring outfit..."],
  ["正在随机还原套装。", "Restoring a random outfit."],
  ["目标不可用", "Target unavailable"],
  ["当前目标不能换装", "The target cannot change outfits now"],
  ["未知NPC", "Unknown NPC"],
  ["性别未知", "Unknown sex"],
  ["未知", "Unknown"],
  ["男性", "Male"], ["女性", "Female"], ["男", "M"], ["女", "F"],
  ["玩家", "Player"],
  ["键盘", "Keyboard"], ["手柄", "Gamepad"],
  ["选择保存位置", "Choose Save Slot"],
  ["保存编辑搭配", "Save Studio Draft"],
  ["材质尚未生成", "Material Not Generated"],
  ["套装内容有缺失", "Outfit Content Missing"],
  ["这个 NPC 可能是共享角色", "This NPC May Be Shared"],
  ["共享 NPC 提醒", "Shared NPC Warning"],
  ["进入服装工作台", "Enter Outfit Studio"],
  ["服装工作台", "Outfit Studio"],
  ["材质交换", "Material Swap"],
  ["可用材质", "Available Materials"],
  ["材质试穿", "Material Preview"],
  ["当前材质", "Current Material"],
  ["扩展匹配", "Extended Match"],
  ["生成物品", "Generate Item"],
  ["试穿材质", "Preview Material"],
  ["选择材质", "Select Material"],
  ["选择一件服装", "Select a Clothing Item"],
  ["可试穿装备或进入材质交换", "Preview the item or open Material Swap"],
  ["当前已穿戴", "Equipped"], ["当前未穿戴", "Not Equipped"],
  ["已穿戴", "Equipped"], ["未穿戴", "Not Equipped"],
  ["穿上/脱下", "Equip/Unequip"], ["穿上", "Equip"], ["脱下", "Unequip"],
  ["选择目标", "Select Target"], ["附近角色", "Nearby Characters"],
  ["玩家与附近 NPC", "Player and Nearby NPCs"],
  ["管理套装", "Manage Outfits"], ["已保存套装", "Saved Outfits"],
  ["确认穿戴", "Confirm Outfit"], ["随机试穿", "Random Preview"],
  ["随机换装", "Random Outfit"],
  ["装备上一套", "Equip Previous Outfit"], ["装备下一套", "Equip Next Outfit"],
  ["装备当前套装", "Equip Active Outfit"], ["当前活跃套装", "Active Outfit"], ["活跃套装", "Active Outfit"],
  ["保存套装", "Save Outfit"], ["命名套装", "Name Outfit"], ["清空保存套装", "Clear Saved Outfit"],
  ["覆盖保存套装", "Overwrite Saved Outfit"], ["套装已保存", "Outfit Saved"],
  ["套装保存失败", "Failed to Save Outfit"], ["套装已清空", "Outfit Cleared"],
  ["清空套装失败", "Failed to Clear Outfit"], ["套装性别不匹配", "Outfit Does Not Match Target"],
  ["该套装为空", "This outfit is empty"], ["该套装已经是空的", "This outfit is already empty"],
  ["空套装", "Empty"], ["套装名称", "Outfit Name"],
  ["名称已保存", "Name Saved"], ["名称保存失败", "Failed to Save Name"],
  ["名称写入失败", "Failed to write the name"], ["槽位名称写入失败", "Failed to write the slot name"],
  ["已恢复默认槽位名称", "Default slot name restored"], ["槽位名称已保存", "Slot name saved"],
  ["空槽位不能命名", "An empty slot cannot be named"],
  ["默认服装", "Default Outfit"], ["恢复默认状态", "Restore Default State"],
  ["已恢复默认服装", "Default Outfit Restored"], ["已恢复默认状态", "Default State Restored"],
  ["更多功能", "More Actions"], ["角色服装维护", "Character Outfit Maintenance"], ["返回主页面", "Return to Main Page"],
  ["系统状态", "System Status"], ["基础功能", "Basic Actions"], ["基础设置", "General Settings"],
  ["武器保存", "Weapon Saving"], ["启用武器保存", "Enable Weapon Saving"], ["显示换装通知", "Show Outfit Notifications"],
  ["提示与确认", "Prompts & Confirmations"], ["工作台提示", "Studio Warning"], ["确认弹窗", "Confirmation Dialogs"],
  ["进入工作台前提示裸露", "Warn About Nudity Before Studio"], ["恢复默认前确认", "Confirm Before Restoring Default"],
  ["清空套装前确认", "Confirm Before Clearing an Outfit"], ["覆盖套装前确认", "Confirm Before Overwriting an Outfit"],
  ["退出试穿前确认", "Confirm Before Leaving Preview"], ["离开工作台前确认", "Confirm Before Leaving Studio"],
  ["离开材质预览前确认", "Confirm Before Leaving Material Preview"],
  ["系统说明", "About"], ["主要功能", "Features"], ["兼容说明", "Compatibility"], ["英文名：Aozora Outfit Management System", "Aozora Outfit Management System NG"],
  ["热键", "Hotkeys"], ["打开/关闭", "Open/Close"],
  ["系统助手", "System Assistant"], ["辐射娘助手", "Assistant"],
  ["套装名称", "Outfit Name"], ["状态", "Status"], ["性别", "Sex"], ["物品数", "Items"], ["物品", "Items"],
  ["数量", "Count"], ["改装", "Mods"], ["距离", "Distance"], ["目标", "Target"],
  ["全部", "All"], ["身体", "Body"], ["腿部", "Legs"], ["下装", "Lower Body"], ["鞋靴", "Footwear"],
  ["配饰", "Accessories"], ["头部", "Head"], ["武器", "Weapons"], ["其他", "Other"],
  ["浏览", "Browse"], ["选择", "Select"], ["确认", "Confirm"], ["执行", "Activate"], ["返回", "Back"], ["关闭", "Close"],
  ["翻页", "Page"], ["详情", "Details"], ["分类", "Category"], ["命名", "Rename"], ["清空", "Clear"], ["保存", "Save"],
  ["继续查看", "Keep Browsing"], ["继续编辑", "Keep Editing"], ["继续调整", "Keep Editing"], ["再看看", "Not Yet"],
  ["不保存", "Don't Save"], ["放弃预览", "Discard Preview"], ["不穿戴并退出", "Exit Without Equipping"],
  ["确认穿戴并退出", "Equip and Exit"], ["应用并退出", "Apply and Exit"], ["不应用并退出", "Exit Without Applying"],
  ["进入工作台", "Enter Studio"], ["先不进去", "Not Now"], ["覆盖保存", "Overwrite"], ["保存下来", "Save It"],
  ["继续穿", "Continue"], ["不穿了", "Don't Equip"], ["继续换装", "Continue"], ["不换了", "Cancel"],
  ["知道了", "Got It"], ["请确认", "Please Confirm"], ["取消", "Cancel"],
  ["读取中", "Loading"], ["等待试穿", "Ready to Preview"], ["同步完成", "Ready"],
  ["正在切换目标", "Switching Target"], ["正在挑选服装，请稍等哦", "Choosing an outfit. Please wait"],
  ["请先选择一件服装", "Select a clothing item first"], ["请先选择一个材质", "Select a material first"],
  ["请先选择已保存套装", "Select a saved outfit first"], ["当前编辑搭配没有变化", "The studio draft has not changed"],
  ["材质预览已更新", "Material Preview Updated"], ["材质预览失败", "Material Preview Failed"],
  ["已生成并穿上材质款", "Material Variant Generated and Equipped"], ["生成材质服装失败", "Failed to Generate Material Variant"],
  ["材质已生成", "Material Generated"], ["材质生成失败", "Failed to Generate Material"],
  ["已退出材质试穿", "Material Preview Closed"], ["材质临时试穿", "Temporary Material Preview"],
  ["材质物品已生成", "Material Item Generated"], ["换装已确认", "Outfit Confirmed"], ["确认换装失败", "Failed to Confirm Outfit"],
  ["正在预览槽位套装", "Previewing Saved Outfit"], ["无法预览此槽位", "Unable to Preview This Slot"],
  ["正在随机预览", "Previewing Random Outfit"], ["随机预览失败", "Random Preview Failed"],
  ["服装预览已更新", "Clothing Preview Updated"], ["无法预览此服装", "Unable to Preview This Item"],
  ["已脱下当前服装", "Item Unequipped"], ["无法脱下此服装", "Unable to Unequip This Item"], ["无法脱下", "Unable to Unequip"],
  ["临时预览已撤销", "Temporary Preview Reverted"], ["已选择目标", "Target Selected"],
  ["已恢复并预览目标默认状态", "Target Default State Restored and Previewed"],
  ["没有记录该目标的默认服装或已管理物品", "No default outfit or managed items were recorded for this target"],
  ["无法建立工作台编辑搭配", "Unable to create a studio draft"], ["可以进入Outfit Studio", "Outfit Studio is available"],
  ["管理槽位已切换至", "Managed slot changed to"], ["管理槽位已清空", "Managed slot cleared"], ["清空管理槽位失败", "Failed to clear managed slot"],
  ["套装已保存至槽位", "Outfit saved to slot"], ["套装", "Outfit"], ["槽位", "Slot"],
  ["已装备", "Equipped"], ["换装失败", "Outfit Change Failed"], ["装备失败", "Equip Failed"],
  ["正在准备中，请稍后再试", "Preparing. Try again shortly"],
];

pairs.sort((a, b) => b[0].length - a[0].length);
for (const file of files) {
  let text = fs.readFileSync(file, "utf8");
  for (const [from, to] of pairs) text = text.split(from).join(to);
  fs.writeFileSync(file, text, "utf8");
}
